sudo: required
services:
	- docker

before_install:
	- docker build -t bubblegumcombo/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true bubblegumcombo/react-test npm test

after_success:
	- docker built -t bubblegumcombo/multi-client ./client
	- docker built -t bubblegumcombo/multi-nginx ./nginx
	- docker built -t bubblegumcombo/multi-server ./server
	- docker built -t bubblegumcombo/multi-worker ./worker
#log into docker cli 
	- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take images and push to docker hub
	- docker push bubblegumcombo/multi-client
	- docker push bubblegumcombo/multi-nginx
	- docker push bubblegumcombo/multi-server
	- docker push bubblegumcombo/multi-worker